spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# ai-service(FastAPI) 연동
ai-service:
  base-url: http://localhost:8000
